### ISSUE TITLE
Table rendering

### ISSUE THREAD

**Issue by mpbelhorn** [practical-scientific-computing/practical-scientific-computing.github.io#10]
Tables are not rendered very well by redcarpet alone because redcarpet cannot attach a class to the table tags it generates without a custom plugin. Github (reasonably) forbids custom plugins. For readability we _really ought_ to be using bootstrap's .table class.

The kramdown renderer can do this. I suggest we move to kramdown as the markdown->html renderer, but this will mess up at least one thing: syntax highlighting for fenced code blocks "```" will not work. Instead, liquid tags will need to be used {% highlight x %} and {% endhighlight %}.

I've got kramdown working on a local branch of the repo and I'm willing to process all the pages created so far to make them kramdown compatible. Let me know what you guys think.

To see what I'm talking about, here is the same table rendered with kramdown+bootstrap class vs redcarpet:

![kramdown](https://cloud.githubusercontent.com/assets/1690817/5996004/8d458928-aa6d-11e4-9ff2-ee2f4591de30.png)
![redcarpet](https://cloud.githubusercontent.com/assets/1690817/5996003/8d44cfa6-aa6d-11e4-9b84-375b1d7bdafa.png)

**Comment by mpbelhorn** [comment]
Oh, and btw, using kramdown to modify the classes attached to rendered markdown will also solve the previous image width problem (issue #9 )  without needing custom css.

**Comment by mpbelhorn** [comment]
I've got the kramdown settings worked out to facilitate highlighting fenced code blocks using the rouge syntax highlighter. Rouge produces code compatible with Pygments css styles but doesn't offer as many languages (still plenty for our needs, though). If you want to use one of pygment's lexers, that will still be available through liquid tags.

I'd love to switch renderers now, but before I do, I'd like to hear any reasons why we shouldn't. Pat did you have a specific reason for going with redcarpet or was it chosen just because it's convenient/default? The switch shouldn't break anything - I've checked how the site is rendered under both redcarpet and kramdown and I couldn't find any major differences.

**Comment by patrickmalsom** [comment]
This is fine on my end. I used redcarpet for convenience only so switching is up to you.

**Comment by mpbelhorn** [comment]
Ok, switched the site to render with kramdown+rouge+ghm. Using GHM mode, there should be no differences in how pages are written UNLESS you want to take advantage of the extra features offered by kramdown. Rouge cannot parse as many languages as pygments, so if you want to have syntax highlighting in an "exotic" language, you must use {% highlight lexer %} ... {% endhighlight %} liquid tags around the code instead of `lexer ...` fencing.
