### ISSUE TITLE
Add an icon to the web interface

### ISSUE THREAD

**Issue by patrickmalsom** [practical-scientific-computing/practical-scientific-computing.github.io#2]
Icon should go in the html head so it will show up in the browser tab. 

Might also want to find a place to put it in the main page, if the icon is nice at least.

**Comment by mpbelhorn** [comment]
You have a favicon for this?

**Comment by patrickmalsom** [comment]
I sure don't. I just like to see some (any unique) icon in the tab on my browser.

Do you have one you want to use?

**Comment by mpbelhorn** [comment]
Nothing comes to mind as being really relevant except stuff with legal
encumbrances. I'll keep my eye out though.
